### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/kflab-bot#38]
```
Traceback (most recent call last):
  File "/home/runner/work/kflab/kflab/./scripts/write_issue_report.py", line 80, in <module>
Starting write_issue_report.py
Number of open Issues: 47
Issue hyperlinks will not be generated.
Number of inactive Issues: 46
Number of assignees in inactive Issues: 10
gh command: gh issue list --limit 1000 --state all --search "updated:2023-01-16..2023-01-23"
Issues updated in the last 7 days: 62, 210, 225, 246, 247, 248, 249, 250
    issue = json.loads(gh_out2.stdout.decode('utf8'))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/json/decoder.py", line [355](https://github.com/kfuku52/kflab/actions/runs/3982954237/jobs/6827863773#step:4:356), in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.
```

**Comment by kfuku52** [comment]
Fixed in https://github.com/kfuku52/kflab-bot/commit/a50717312ebc5a4c02fed22061093d96478575b4
